{{- if not .Values.app.volume.hostPath }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "lookout-style-analyzer.fullname" . }}
  name: {{ template "lookout-style-analyzer.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.app.volume.pvc.storageClassName }}
  storageClassName: {{ .Values.app.volume.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.volume.pvc.size }}
{{- end }}
