apiVersion: v1
kind: ConfigMap
metadata:
  name: "nginx-config"
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /dev/stderr warn;
    pid        /var/run/nginx.pid;


    events {
      worker_connections  1024;
    }

    http {
      #include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /dev/stdout  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      include /etc/nginx/conf.d/*.conf;

      server {
        listen {{ .Values.Nginx.Port }};
        location /github-webhook/ {
          proxy_pass http://localhost:{{ .Values.Master.ServicePort }}/;
          proxy_set_header X-Real-IP $remote_addr;
          limit_except POST {
            deny all;
          }
        }
      }
    }
