{{- if .Values.deployDummyAnalyzer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "lookout.fullname" . }}-dummy-analyzer
  labels:
    app: dummy-analyzer
    chart: {{ template "lookout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.dummyAnalyzer.type }}
  ports:
    - port: {{ .Values.service.dummyAnalyzer.port }}
      targetPort: {{ .Values.app.dummyAnalyzer.port }}
      protocol: TCP
  selector:
    app: dummy-analyzer
    release: {{ .Release.Name }}
{{- end }}
