apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "lookout.fullname" . }}-dummy-analyzer
  labels:
    app: dummy-analyzer
    chart: {{ template "lookout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.dummyAnalyzer }}
  selector:
    matchLabels:
      app: dummy-analyzer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: dummy-analyzer
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: dummy-analyzer
          image: "{{ .Values.image.dummyAnalyzer.repository }}:{{ .Values.image.dummyAnalyzer.tag }}"
          imagePullPolicy: {{ .Values.image.dummyAnalyzer.pullPolicy }}
          args:
            - serve
            - {{ .Values.app.lookout.repository }}
          env:
            - name: LOOKOUT_DATA_SERVER
              value: "ipv4://{{ template "lookout.fullname" . }}:{{ .Values.service.lookout.port }}"
            - name: LOOKOUT_ANALYZER
              value: "ipv4://0.0.0.0:{{ .Values.app.dummyAnalyzer.port }}"
          ports:
            - containerPort: {{ .Values.app.dummyAnalyzer.port }}
              protocol: TCP
          # TODO: These are bare-minimum probes. We should have something better
          livenessProbe:
            tcpSocket:
              port: {{ .Values.app.dummyAnalyzer.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.app.dummyAnalyzer.port }}
          resources:
{{ toYaml .Values.resources.dummyAnalyzer | indent 12 }}
    {{- with .Values.nodeSelector.dummyAnalyzer }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity.dummyAnalyzer }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations.dummyAnalyzer }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
