kind: Service
apiVersion: v1
metadata:
  name: landing-load-balancer
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  labels:
    app: landing-load-balancer
spec:
  type: LoadBalancer
  loadBalancerIP: 130.211.75.214
  selector:
    app: landing-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
