apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: landing-slackin
  labels:
    app: landing-slackin
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.landingSlackin }}
  template:
    metadata:
      labels:
        app: landing-slackin
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.landingSlackin.repository }}:{{ .Values.image.landingSlackin.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: slack-api-token
          ports:
            - containerPort: {{ .Values.service.landingSlackin.internalPort }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.landingSlackin.internalPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.landingSlackin.internalPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: srcd-jbeardly-pull-secret
