apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.landingStatic.externalPort }}
      targetPort: {{ .Values.service.landingStatic.internalPort }}
      protocol: TCP
      name: {{ .Values.service.landingStatic.name }}
    - port: {{ .Values.service.landingSlackin.externalPort }}
      targetPort: {{ .Values.service.landingSlackin.internalPort }}
      protocol: TCP
      name: {{ .Values.service.landingSlackin.name }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
